# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Math challenges
email: terabaud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a place where I try to solve various math challenges from project euler. 
  At this point, there is nearly no content here yet. I'm just getting started with Jekyll, 
  the blog-aware static site generator that power GitHub Pages; I still have to figure out 
  how to add interactive code snippets and spoiler buttons (hide the solution until you press a spoiler button)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://terabaud.github.io/math-challenges" # the base hostname & protocol for your site
twitter_username: terabaud
github_username:  terabaud

# Build settings
markdown: kramdown
